version: '3.8'

services:

  caritas_database_pgsql:
    image: postgres:13
    container_name: container_caritas_database_pgsql
    environment:
      POSTGRES_DB: caritas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data_pgsql_caritas:/var/lib/postgresql/data
    networks:
      - caritas_network

volumes:
  db_data_pgsql_caritas:

networks:
  caritas_network:
    driver: bridge